### ISSUE TITLE
add dcat:endpointDescription to the mapping-table in README.md

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/openapiparser#2]
dcat:endpointDescription should be added to the mapping-table in the README. It maps to the URL of the OAS-file.

https://www.w3.org/TR/vocab-dcat-2/#Property:data_service_endpoint_description

"An endpoint description may be expressed in a machine-readable form, such as an OpenAPI (Swagger) description [...]"

**Comment by stigbd** [comment]
Fixed in 0396652
