### ISSUE TITLE
dct:mediatype is not part of the resulting rdf

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/openapiparser#4]
After using oastodcat to read an OAS-file that includes content-specifications that are stored in the attribute media_types, the media_types exists, but they are not part of the resulting rdf:

```
>>> gc.catalog.services[0].media_types
['https://www.iana.org/assignments/media-types/type', 'https://www.iana.org/assignments/media-types/description', 'https://www.iana.org/assignments/media-types/application/json']
>>> >>> gc.catalog.services[0].to_rdf().decode()
'@prefix dcat: <http://www.w3.org/ns/dcat#> .\n@prefix dct: <http://purl.org/dc/terms/> .\n\n<https://ebevis.no> a dcat:DataService ;\n    dct:description "API for eBevis - production environment"@en ;\n    dct:title "eBevis Production"@en ;\n    dcat:endpointURL <https://api.ebevis.no/nadobe/v1> ;\n    dcat:landingPage <http://enurl.com> .\n\n'
>>> 
```

https://github.com/Informasjonsforvaltning/oastodcat/blob/cba8abfb075b3c5e4ee4e5e65c4a9cac11c1290d/src/oastodcat/oas_dataservice.py#L32

**Comment by stigbd** [comment]
I am not able to reproduce this. Can you verify that you have the latest version of datactalogtordf (1.0.3) installed?
